### ISSUE TITLE
--mode=git doesn't work on 2.11.1

### ISSUE THREAD

**Issue by MichaelB-99** [tiged/tiged#39]
As of 2.11.1 ```--mode=git``` doesn't work, at least on windows:

![degit-failure](https://user-images.githubusercontent.com/54602790/166518691-c61590d8-6107-4313-add6-28de4d8f322b.png)

However, after downgrading to 2.11.0, it works as expected:

![degit-success](https://user-images.githubusercontent.com/54602790/166519436-0072188c-9d44-436e-8f9b-331849a61333.png)

Thanks for all your hard work on tiged btw!

**Comment by nake89** [comment]
Oh my. I'll look into this.

**Comment by nake89** [comment]
It would seem that on line 348 `if (this.repo.ref)` is true with your command line input. Interesting. That is definitely a bug of its own.

That said, commits related to: Add ability to use old hashes with --mode=git. (https://github.com/tiged/tiged/pull/34) broke this, because it is not cross platform friendly.

Quickest way to fix it is put OS check there and run it the old way if Windows.
And also definitely fix the first bug I mentioned at the same time.

Currently automated testing is done on github actions with linux as os only. I could add windows and mac there if it is free. That is definitely a ticket of its own: #40

**Comment by nake89** [comment]
I'm basically rubberducking here (so please turn notifications off for this thread if you don't want to read my _thinking out loud_, I just find writing things down or saying them out loud helps me think.)

Right so apparently `this.repo.ref = 'HEAD'` even if no ref is given. I guess that makes sense...
So switching to
```
if (this.repo.ref && this.repo.ref !== 'HEAD')
```
instead of
```
if (this.repo.ref)
```
should at least fix that error.

On to adding the OS detection.
