### ISSUE TITLE
Huggingface.co support

### ISSUE THREAD

**Issue by nake89** [tiged/tiged#59]
Somebody already did a PR at degit: https://github.com/Rich-Harris/degit/pull/333

**Comment by severo** [comment]
Thanks a lot for bringing the PR here.

I tried it, and it works well in most cases.

But it's broken on some Hugging Face repositories because the expectation `user/repo` does not work for all of them.

Indeed, the Hub supports [three types of repositories](https://huggingface.co/docs/hub/): "models", "datasets", and "spaces". Dataset repos are always prefixed with `datasets/` and space repos with `spaces/`, while model repos are not for historical reasons. And the repos can be "canonical" (`repo`) or namespaced inside a user or organization (`user/repo`, `org/repo`). It means that all the following repository id are valid:

```
repo
user/repo
datasets/repo
datasets/user/repo
spaces/repo
spaces/user/repo
```

I'll work on a PR to try to fix it.

**Comment by severo** [comment]
It will not be easy to manage both the canonical/non-canonical repositories and the "subdir" feature of tiged.

I would be in favor of not supporting subdirs on canonical repos for huggingface. Possibly they will be moved to namespaced repositories soon anyway. Also: I was not able to find any canonical model repo with sub-directories (all the files are at the root), and there are no canonical spaces, so: it will only affect the canonical datasets meanwhile, not a big deal I think.

**Comment by nake89** [comment]
Closing this for now. There is hugging face support. It might not be perfect but good for now. Any issues that anybody might have or any PRs are welcome :)
